export default {
  // BASIC
  UPDATED: 'UPDATED',
  // FAVORITE JOKES
  ADD_FAVORITE_JOKE: 'ADD_FAVORITE_JOKE',
  ADD_RANDOM_FAVORITE_JOKE: 'GET_RANDOM_FAVORITE_JOKE',
  DELETE_FAVORITE_JOKE: 'DELETE_FAVORITE_JOKE',
  // RANDOM JOKES
  GET_RANDOM_JOKES: 'GET_RANDOM_JOKES',
};
